# SLP Simple Examples

In [1]:
import numpy as np
from slp import SLP
from utils import add_noise

## 1. AND Gate Dataset

### Create The Dataset

In [2]:
X = np.array(
    [
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1],
    ]
)
y = np.array([0, 1, 1, 1])

### Fit A Network

In [3]:
my_slp = SLP(X, y, epochs=5, learning_rate=0.3)
my_slp.fit()


############ Training Process Started ############
---- Epoch 1
Error = 1
---- Epoch 2
Error = 1
---- Epoch 3
Error = 1
---- Epoch 4
Error = 1
---- Epoch 5
Error = 1
############# Training Process Ended #############


### Evaluation

In [4]:
print("Prediction for the last row of X:", my_slp.predict(X[-1]))
print("Predictions for first 2 rows of X:", my_slp.predict(X[:2]))


Prediction for the last row of X: [1]
Predictions for first 2 rows of X: [1 1]


In [5]:
my_slp.evaluate(X, y)


idx   X       Target  Pred
0     [0 0]   0       1   
1     [0 1]   1       1   
2     [1 0]   1       1   
3     [1 1]   1       1   

Accuracy = 0.75


## 2. 'I' And 'L' Character Classification

A network to classify 'I' and 'L' characters.

### Create The Dataset

In [6]:
# Create the characters
L = np.array(
    [
     [1, 0, 0],
     [1, 0, 0],
     [1, 1, 1]
     ]
)

I = np.array(
    [
     [0, 1, 0],
     [0, 1, 0],
     [0, 1, 0]
    ]
)

In [7]:
# Create the inputs and outputs of the network
X = np.asarray([L.flatten(), I.flatten()])
y = np.array([0, 1])

In [8]:
# Make two noisy datasets
X_noisy = np.asarray([add_noise(X[0], 0.25), add_noise(X[1], 0.25)])
X_very_noisy = np.asarray([add_noise(X[0], 0.5), add_noise(X[1], 0.5)])

In [9]:
# X_noisy
print(f"L:\n{X_noisy[0].reshape((3, 3))}\nI:\n{X_noisy[1].reshape((3, 3))}")

L:
[[1 1 0]
 [1 0 0]
 [1 0 1]]
I:
[[1 1 0]
 [0 1 0]
 [0 0 0]]


In [10]:
# X_very_noisy
print(f"L:\n{X_very_noisy[0].reshape((3, 3))}\nI:\n{X_very_noisy[1].reshape((3, 3))}")

L:
[[1 0 0]
 [1 1 1]
 [1 1 1]]
I:
[[0 1 0]
 [0 1 0]
 [1 0 0]]


### Fit A Network

In [11]:
my_slp = SLP(X, y, epochs=5, learning_rate=0.3)
my_slp.fit()

############ Training Process Started ############
---- Epoch 1
Error = 1
---- Epoch 2
Error = 0
---- Epoch 3
Error = 0
---- Epoch 4
Error = 0
---- Epoch 5
Error = 0
############# Training Process Ended #############


### Evaluation

In [12]:
my_slp.evaluate(X, y)


idx   X                     Target  Pred
0     [1 0 0 1 0 0 1 1 1]   0       0   
1     [0 1 0 0 1 0 0 1 0]   1       1   

Accuracy = 1.0


In [13]:
my_slp.evaluate(X_noisy, y)


idx   X                     Target  Pred
0     [1 1 0 1 0 0 1 0 1]   0       0   
1     [1 1 0 0 1 0 0 0 0]   1       1   

Accuracy = 1.0


In [14]:
my_slp.evaluate(X_very_noisy, y)


idx   X                     Target  Pred
0     [1 0 0 1 1 1 1 1 1]   0       0   
1     [0 1 0 0 1 0 1 0 0]   1       1   

Accuracy = 1.0
